FROM php:7.2-apache
COPY src/ /var/www/html/

# docker build -t my-php-app .
# docker run -p 80:80 --name my-running-app my-php-app

# without dockerfile
# docker run -p 80:80 --name my-apache-php-app -v "$PWD":/var/www/html php:7.2-apache