version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ilbonzo-server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "0.0.0.0:5000:3000"
    links:
      - "db:database"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ilbonzo-client
    volumes:
      - ./client:/srv/nodejs/app
    ports:
      - "0.0.0.0:3000:3000"
    stdin_open: true
  db:
    image: postgres:12.1-alpine
    container_name: ilbonzo-db
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
        - "5432:5432"
