---
# tasks file for loadbalancer
- name: edit /etc/hosts
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ item.ip }} {{ item.name }}"
  with_items:
    - { ip: 172.31.25.35, name: web_server_1 }
    - { ip: 172.31.22.40, name: web_server_2 }
  tags:
    - no-docker

- name: install nginx
  apt:
    name=nginx
    state=present
    update_cache=yes

- name: ensure nginx is started
  service:
    name=nginx
    state=started
    enabled=yes

- name: config nginx site
  template:
    src=templates/nginx.conf.j2
    dest=/etc/nginx/sites-available/demo
    mode=0644
  notify: restart nginx

- name: de-activate default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

- name: activate demo nginx site
  file:
    src=/etc/nginx/sites-available/demo
    dest=/etc/nginx/sites-enabled/demo
    state=link
  notify: restart nginx